apiVersion: v1
data:
  config.yaml: |-
    hook-mode: auto
    fallback-pod-informer: true
    events-buffer-length: 16384
    containerd-socketpath: /run/containerd/containerd.sock
    crio-socketpath: /run/crio/crio.sock
    docker-socketpath: /run/docker.sock
    podman-socketpath: /run/podman/podman.sock
    operator:
      oci:
        verify-image: true
        public-keys:
          - |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEoDOC0gYSxZTopenGmX3ZFvQ1DSfh
            Ir4EKRt5jC+mXaJ7c7J+oREskYMn/SfZdRHNSOjLTZUMDm60zpXGhkFecg==
            -----END PUBLIC KEY-----
        allowed-gadgets:
          []
        disallow-pulling: false
      otel-metrics:
          exporters:
            metric-exporter:
              exporter: otlp-grpc
              endpoint: "otel-collector.default.svc.cluster.local:4317"
              insecure: true
              temporality: delta
              interval: 30s
      otel-logs:
          exporters:
            my-log-exporter:
              exporter: otlp-grpc
              compression: gzip
              endpoint: "otel-collector.default.svc.cluster.local:4317"
              insecure: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: gadget
    meta.helm.sh/release-namespace: gadget
  labels:
    app.kubernetes.io/managed-by: Helm
  name: gadget
  namespace: gadget

