apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
  namespace: gadget
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-pods
  namespace: gadget
rules:
  - apiGroups: [""]
    resources:
      - events
      - namespaces
      - namespaces/status
      - nodes
      - nodes/spec
      - nodes/stats
      - nodes/proxy
      - pods
      - pods/status
      - pods/portforward
      - replicationcontrollers
      - replicationcontrollers/status
      - resourcequotas
      - services
      - endpoints
    verbs: ["get", "list", "watch","create"]
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["namespaces", "nodes", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["services"]
    # list is needed by network-policy gadget
    # watch is needed by operators enriching with service informations
    verbs: ["list", "watch"]
  - apiGroups: ["gadget.kinvolk.io"]
    resources: ["traces", "traces/status"]
    # For traces, we need all rights on them as we define this resource.
    verbs: ["delete", "deletecollection", "get", "list", "patch", "create", "update", "watch"]
  - apiGroups: ["*"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets", "jobs", "cronjobs", "replicationcontrollers"]
    # Required to retrieve the owner references used by the seccomp gadget.
    verbs: ["get"]
  - apiGroups: ["security-profiles-operator.x-k8s.io"]
    resources: ["seccompprofiles"]
    # Required for integration with the Kubernetes Security Profiles Operator
    verbs: ["list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-pods-to-sa
roleRef:
  kind: ClusterRole
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: internal-kubectl
    namespace: gadget
---
apiVersion: batch/v1
kind: Job
metadata:
  name: ebpftop
spec:
    ttlSecondsAfterFinished: 100
    template:
      spec:
        serviceAccountName: internal-kubectl
        restartPolicy: Never
        containers:
          - name: tester
            image: hrexed/kubectlgadget:0.6
            command:
              - "/bin/bash"
              - "./ebpf_top.sh"